version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      npm-deps:
        patterns:
          - "*"
    labels:
      - dependencies
      - javascript

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      python-deps:
        patterns:
          - "*"
    labels:
      - dependencies
      - python

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
