import os

OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen3.5:4b-q4_K_M")
OLLAMA_TIMEOUT = int(os.getenv("OLLAMA_TIMEOUT", "600"))
OLLAMA_NUM_CTX = int(os.getenv("OLLAMA_NUM_CTX", "4096"))
OLLAMA_GENERATE_NUM_PREDICT = int(os.getenv("OLLAMA_GENERATE_NUM_PREDICT", "8192"))
GMAIL_MAX_RESULTS = int(os.getenv("GMAIL_MAX_RESULTS", "50"))
GMAIL_LOOKBACK_HOURS = int(os.getenv("GMAIL_LOOKBACK_HOURS", "24"))
EMAIL_BODY_TRUNCATION = int(os.getenv("EMAIL_BODY_TRUNCATION", "3000"))
LOG_RETENTION_DAYS = int(os.getenv("LOG_RETENTION_DAYS", "30"))
POLL_INTERVAL = int(os.getenv("POLL_INTERVAL", "300"))
MIN_POLL_INTERVAL = int(os.getenv("MIN_POLL_INTERVAL", "30"))
HISTORY_MAX_LIMIT = int(os.getenv("HISTORY_MAX_LIMIT", "500"))
DEBUG_LOGGING = os.getenv("DEBUG_LOGGING", "0") == "1"
