// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Account struct {
	ID              int64
	Email           string
	CredentialsJson string
	AddedAt         string
	LastScanAt      sql.NullString
	Active          int64
}

type AccountRetention struct {
	AccountID  int64
	GlobalDays sql.NullInt64
}

type CategorizationHistory struct {
	ID           int64
	Timestamp    string
	AccountID    int64
	AccountEmail string
	MessageID    string
	Subject      string
	Sender       string
	PromptID     sql.NullInt64
	PromptName   sql.NullString
	LabelName    sql.NullString
	Actions      string
	LlmResponse  string
}

type EmailCorrection struct {
	ID               int64
	CreatedAt        string
	AccountID        int64
	MessageID        string
	AddedPrompts     string
	RemovedPrompts   string
	CurrentPromptIds string
	Note             string
}

type LabelExemption struct {
	ID        int64
	AccountID int64
	LabelName string
}

type LabelRetention struct {
	ID        int64
	AccountID int64
	LabelName string
	Days      int64
}

type LlmDebug struct {
	ID           int64
	Timestamp    string
	AccountID    int64
	AccountEmail string
	MessageID    string
	Subject      string
	Sender       string
	GmailRaw     string
	LlmRequest   string
	LlmResponse  string
}

type Log struct {
	ID        int64
	Timestamp string
	Level     string
	Message   string
}

type ProcessedEmail struct {
	ID          int64
	AccountID   int64
	MessageID   string
	ProcessedAt sql.NullString
}

type Prompt struct {
	ID             int64
	Name           string
	Instructions   string
	LabelName      string
	Active         int64
	CreatedAt      string
	ActionArchive  int64
	ActionSpam     int64
	ActionTrash    int64
	ActionMarkRead int64
	SortOrder      int64
	StopProcessing int64
	AccountID      sql.NullInt64
}

type PromptSuggestion struct {
	ID                    int64
	CreatedAt             string
	UpdatedAt             string
	PromptID              int64
	CorrectionID          sql.NullInt64
	TriggerKind           string
	MessageID             string
	EmailSubject          string
	EmailSender           string
	EmailBodySnapshot     string
	OriginalInstructions  string
	SuggestedInstructions string
	ConversationJson      string
	UserComment           string
	Status                string
}

type SchemaVersion struct {
	Version int64
}

type Setting struct {
	Key   string
	Value string
}
