// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addHistory = `-- name: AddHistory :exec

INSERT INTO categorization_history
    (account_id, account_email, message_id, subject, sender, prompt_id, prompt_name, label_name, actions, llm_response)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddHistoryParams struct {
	AccountID    int64
	AccountEmail string
	MessageID    string
	Subject      string
	Sender       string
	PromptID     sql.NullInt64
	PromptName   sql.NullString
	LabelName    sql.NullString
	Actions      string
	LlmResponse  string
}

// ============================================================
// Categorization History
// ============================================================
func (q *Queries) AddHistory(ctx context.Context, arg AddHistoryParams) error {
	_, err := q.db.ExecContext(ctx, addHistory,
		arg.AccountID,
		arg.AccountEmail,
		arg.MessageID,
		arg.Subject,
		arg.Sender,
		arg.PromptID,
		arg.PromptName,
		arg.LabelName,
		arg.Actions,
		arg.LlmResponse,
	)
	return err
}

const addLabelExemption = `-- name: AddLabelExemption :exec
INSERT INTO label_exemptions (account_id, label_name) VALUES (?, ?)
ON CONFLICT(account_id, label_name) DO NOTHING
`

type AddLabelExemptionParams struct {
	AccountID int64
	LabelName string
}

func (q *Queries) AddLabelExemption(ctx context.Context, arg AddLabelExemptionParams) error {
	_, err := q.db.ExecContext(ctx, addLabelExemption, arg.AccountID, arg.LabelName)
	return err
}

const addLabelRetention = `-- name: AddLabelRetention :exec
INSERT INTO label_retention (account_id, label_name, days) VALUES (?, ?, ?)
ON CONFLICT(account_id, label_name) DO UPDATE SET days = excluded.days
`

type AddLabelRetentionParams struct {
	AccountID int64
	LabelName string
	Days      int64
}

func (q *Queries) AddLabelRetention(ctx context.Context, arg AddLabelRetentionParams) error {
	_, err := q.db.ExecContext(ctx, addLabelRetention, arg.AccountID, arg.LabelName, arg.Days)
	return err
}

const addLlmDebug = `-- name: AddLlmDebug :exec


INSERT INTO llm_debug (account_id, account_email, message_id, subject, sender, gmail_raw, llm_request, llm_response)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AddLlmDebugParams struct {
	AccountID    int64
	AccountEmail string
	MessageID    string
	Subject      string
	Sender       string
	GmailRaw     string
	LlmRequest   string
	LlmResponse  string
}

// ============================================================
// Schema version
// ============================================================
// ============================================================
// LLM Debug
// ============================================================
func (q *Queries) AddLlmDebug(ctx context.Context, arg AddLlmDebugParams) error {
	_, err := q.db.ExecContext(ctx, addLlmDebug,
		arg.AccountID,
		arg.AccountEmail,
		arg.MessageID,
		arg.Subject,
		arg.Sender,
		arg.GmailRaw,
		arg.LlmRequest,
		arg.LlmResponse,
	)
	return err
}

const addLog = `-- name: AddLog :exec

INSERT INTO logs (level, message) VALUES (?, ?)
`

type AddLogParams struct {
	Level   string
	Message string
}

// ============================================================
// Logs
// ============================================================
func (q *Queries) AddLog(ctx context.Context, arg AddLogParams) error {
	_, err := q.db.ExecContext(ctx, addLog, arg.Level, arg.Message)
	return err
}

const applyPromptSuggestion = `-- name: ApplyPromptSuggestion :exec
UPDATE prompt_suggestions SET status = 'applied', updated_at = strftime('%Y-%m-%d %H:%M:%S', 'now')
WHERE id = ?
`

func (q *Queries) ApplyPromptSuggestion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, applyPromptSuggestion, id)
	return err
}

const clearGlobalRetention = `-- name: ClearGlobalRetention :exec
DELETE FROM account_retention WHERE account_id = ?
`

func (q *Queries) ClearGlobalRetention(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, clearGlobalRetention, accountID)
	return err
}

const countActivePrompts = `-- name: CountActivePrompts :one
SELECT COUNT(*) FROM prompts WHERE active = 1
`

func (q *Queries) CountActivePrompts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePrompts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingPromptSuggestions = `-- name: CountPendingPromptSuggestions :one
SELECT COUNT(*) FROM prompt_suggestions WHERE status = 'pending'
`

func (q *Queries) CountPendingPromptSuggestions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingPromptSuggestions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountPlaceholder = `-- name: CreateAccountPlaceholder :one
INSERT OR IGNORE INTO accounts (email, credentials_json, active) VALUES (?, '', 1)
RETURNING id
`

func (q *Queries) CreateAccountPlaceholder(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAccountPlaceholder, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPrompt = `-- name: CreatePrompt :one
INSERT INTO prompts (name, instructions, label_name, active, action_archive, action_spam, action_trash, action_mark_read, sort_order, stop_processing, account_id)
VALUES (?, ?, ?, 1, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreatePromptParams struct {
	Name           string
	Instructions   string
	LabelName      string
	ActionArchive  int64
	ActionSpam     int64
	ActionTrash    int64
	ActionMarkRead int64
	SortOrder      int64
	StopProcessing int64
	AccountID      sql.NullInt64
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPrompt,
		arg.Name,
		arg.Instructions,
		arg.LabelName,
		arg.ActionArchive,
		arg.ActionSpam,
		arg.ActionTrash,
		arg.ActionMarkRead,
		arg.SortOrder,
		arg.StopProcessing,
		arg.AccountID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteAccountRetention = `-- name: DeleteAccountRetention :exec
DELETE FROM account_retention WHERE account_id = ?
`

func (q *Queries) DeleteAccountRetention(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccountRetention, accountID)
	return err
}

const deleteHistoryByAccount = `-- name: DeleteHistoryByAccount :exec
DELETE FROM categorization_history WHERE account_id = ?
`

func (q *Queries) DeleteHistoryByAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, deleteHistoryByAccount, accountID)
	return err
}

const deleteLabelExemption = `-- name: DeleteLabelExemption :exec
DELETE FROM label_exemptions WHERE id = ? AND account_id = ?
`

type DeleteLabelExemptionParams struct {
	ID        int64
	AccountID int64
}

func (q *Queries) DeleteLabelExemption(ctx context.Context, arg DeleteLabelExemptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteLabelExemption, arg.ID, arg.AccountID)
	return err
}

const deleteLabelExemptionsByAccount = `-- name: DeleteLabelExemptionsByAccount :exec
DELETE FROM label_exemptions WHERE account_id = ?
`

func (q *Queries) DeleteLabelExemptionsByAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLabelExemptionsByAccount, accountID)
	return err
}

const deleteLabelRetention = `-- name: DeleteLabelRetention :exec
DELETE FROM label_retention WHERE id = ? AND account_id = ?
`

type DeleteLabelRetentionParams struct {
	ID        int64
	AccountID int64
}

func (q *Queries) DeleteLabelRetention(ctx context.Context, arg DeleteLabelRetentionParams) error {
	_, err := q.db.ExecContext(ctx, deleteLabelRetention, arg.ID, arg.AccountID)
	return err
}

const deleteLabelRetentionByAccount = `-- name: DeleteLabelRetentionByAccount :exec
DELETE FROM label_retention WHERE account_id = ?
`

func (q *Queries) DeleteLabelRetentionByAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLabelRetentionByAccount, accountID)
	return err
}

const deleteProcessedEmailsByAccount = `-- name: DeleteProcessedEmailsByAccount :exec
DELETE FROM processed_emails WHERE account_id = ?
`

func (q *Queries) DeleteProcessedEmailsByAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProcessedEmailsByAccount, accountID)
	return err
}

const deletePrompt = `-- name: DeletePrompt :exec
DELETE FROM prompts WHERE id = ?
`

func (q *Queries) DeletePrompt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePrompt, id)
	return err
}

const deletePromptsByAccount = `-- name: DeletePromptsByAccount :exec

DELETE FROM prompts WHERE account_id = ?
`

// ============================================================
// Cascade delete helpers (called manually in a transaction)
// ============================================================
func (q *Queries) DeletePromptsByAccount(ctx context.Context, accountID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deletePromptsByAccount, accountID)
	return err
}

const dismissPromptSuggestion = `-- name: DismissPromptSuggestion :exec
UPDATE prompt_suggestions SET status = 'dismissed', updated_at = strftime('%Y-%m-%d %H:%M:%S', 'now')
WHERE id = ?
`

func (q *Queries) DismissPromptSuggestion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, dismissPromptSuggestion, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, email, credentials_json, added_at, last_scan_at, active
FROM accounts WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CredentialsJson,
		&i.AddedAt,
		&i.LastScanAt,
		&i.Active,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id FROM accounts WHERE email = ? LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAccountRetention = `-- name: GetAccountRetention :one

SELECT account_id, global_days FROM account_retention WHERE account_id = ? LIMIT 1
`

// ============================================================
// Retention
// ============================================================
func (q *Queries) GetAccountRetention(ctx context.Context, accountID int64) (AccountRetention, error) {
	row := q.db.QueryRowContext(ctx, getAccountRetention, accountID)
	var i AccountRetention
	err := row.Scan(&i.AccountID, &i.GlobalDays)
	return i, err
}

const getAllSettings = `-- name: GetAllSettings :many
SELECT key, value FROM settings
`

func (q *Queries) GetAllSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, getAllSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistory = `-- name: GetHistory :many
SELECT id, timestamp, account_id, account_email, message_id, subject, sender,
       prompt_id, prompt_name, label_name, actions, llm_response
FROM categorization_history
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) GetHistory(ctx context.Context, limit int64) ([]CategorizationHistory, error) {
	rows, err := q.db.QueryContext(ctx, getHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategorizationHistory
	for rows.Next() {
		var i CategorizationHistory
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.AccountID,
			&i.AccountEmail,
			&i.MessageID,
			&i.Subject,
			&i.Sender,
			&i.PromptID,
			&i.PromptName,
			&i.LabelName,
			&i.Actions,
			&i.LlmResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoryByAccount = `-- name: GetHistoryByAccount :many
SELECT id, timestamp, account_id, account_email, message_id, subject, sender,
       prompt_id, prompt_name, label_name, actions, llm_response
FROM categorization_history
WHERE account_id = ?
ORDER BY id DESC
LIMIT ?
`

type GetHistoryByAccountParams struct {
	AccountID int64
	Limit     int64
}

func (q *Queries) GetHistoryByAccount(ctx context.Context, arg GetHistoryByAccountParams) ([]CategorizationHistory, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryByAccount, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategorizationHistory
	for rows.Next() {
		var i CategorizationHistory
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.AccountID,
			&i.AccountEmail,
			&i.MessageID,
			&i.Subject,
			&i.Sender,
			&i.PromptID,
			&i.PromptName,
			&i.LabelName,
			&i.Actions,
			&i.LlmResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoryByPrompt = `-- name: GetHistoryByPrompt :many
SELECT id, timestamp, account_id, account_email, message_id, subject, sender,
       prompt_id, prompt_name, label_name, actions, llm_response
FROM categorization_history
WHERE prompt_id = ?
ORDER BY id DESC
LIMIT ?
`

type GetHistoryByPromptParams struct {
	PromptID sql.NullInt64
	Limit    int64
}

func (q *Queries) GetHistoryByPrompt(ctx context.Context, arg GetHistoryByPromptParams) ([]CategorizationHistory, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryByPrompt, arg.PromptID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategorizationHistory
	for rows.Next() {
		var i CategorizationHistory
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.AccountID,
			&i.AccountEmail,
			&i.MessageID,
			&i.Subject,
			&i.Sender,
			&i.PromptID,
			&i.PromptName,
			&i.LabelName,
			&i.Actions,
			&i.LlmResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoryRow = `-- name: GetHistoryRow :one

SELECT id, timestamp, account_id, account_email, message_id, subject, sender,
       prompt_id, prompt_name, label_name, actions, llm_response
FROM categorization_history WHERE id = ? LIMIT 1
`

// ============================================================
// Categorization History (additional)
// ============================================================
func (q *Queries) GetHistoryRow(ctx context.Context, id int64) (CategorizationHistory, error) {
	row := q.db.QueryRowContext(ctx, getHistoryRow, id)
	var i CategorizationHistory
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.AccountID,
		&i.AccountEmail,
		&i.MessageID,
		&i.Subject,
		&i.Sender,
		&i.PromptID,
		&i.PromptName,
		&i.LabelName,
		&i.Actions,
		&i.LlmResponse,
	)
	return i, err
}

const getHistoryUncategorized = `-- name: GetHistoryUncategorized :many
SELECT id, timestamp, account_id, account_email, message_id, subject, sender,
       prompt_id, prompt_name, label_name, actions, llm_response
FROM categorization_history
WHERE prompt_id IS NULL
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) GetHistoryUncategorized(ctx context.Context, limit int64) ([]CategorizationHistory, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryUncategorized, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategorizationHistory
	for rows.Next() {
		var i CategorizationHistory
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.AccountID,
			&i.AccountEmail,
			&i.MessageID,
			&i.Subject,
			&i.Sender,
			&i.PromptID,
			&i.PromptName,
			&i.LabelName,
			&i.Actions,
			&i.LlmResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabelExemptions = `-- name: GetLabelExemptions :many
SELECT id, account_id, label_name FROM label_exemptions
WHERE account_id = ? ORDER BY label_name ASC
`

func (q *Queries) GetLabelExemptions(ctx context.Context, accountID int64) ([]LabelExemption, error) {
	rows, err := q.db.QueryContext(ctx, getLabelExemptions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabelExemption
	for rows.Next() {
		var i LabelExemption
		if err := rows.Scan(&i.ID, &i.AccountID, &i.LabelName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabelRetention = `-- name: GetLabelRetention :many
SELECT id, account_id, label_name, days FROM label_retention
WHERE account_id = ? ORDER BY id ASC
`

func (q *Queries) GetLabelRetention(ctx context.Context, accountID int64) ([]LabelRetention, error) {
	rows, err := q.db.QueryContext(ctx, getLabelRetention, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabelRetention
	for rows.Next() {
		var i LabelRetention
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.LabelName,
			&i.Days,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCorrectionForMessage = `-- name: GetLatestCorrectionForMessage :one
SELECT id, created_at, account_id, message_id, added_prompts, removed_prompts, current_prompt_ids, note
FROM email_corrections
WHERE message_id = ?
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestCorrectionForMessage(ctx context.Context, messageID string) (EmailCorrection, error) {
	row := q.db.QueryRowContext(ctx, getLatestCorrectionForMessage, messageID)
	var i EmailCorrection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.AccountID,
		&i.MessageID,
		&i.AddedPrompts,
		&i.RemovedPrompts,
		&i.CurrentPromptIds,
		&i.Note,
	)
	return i, err
}

const getLatestLlmDebug = `-- name: GetLatestLlmDebug :many
SELECT id, timestamp, account_id, account_email, message_id, subject, sender, gmail_raw, llm_request, llm_response
FROM llm_debug ORDER BY id DESC LIMIT 3
`

func (q *Queries) GetLatestLlmDebug(ctx context.Context) ([]LlmDebug, error) {
	rows, err := q.db.QueryContext(ctx, getLatestLlmDebug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmDebug
	for rows.Next() {
		var i LlmDebug
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.AccountID,
			&i.AccountEmail,
			&i.MessageID,
			&i.Subject,
			&i.Sender,
			&i.GmailRaw,
			&i.LlmRequest,
			&i.LlmResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogs = `-- name: GetLogs :many
SELECT id, timestamp, level, message
FROM logs
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) GetLogs(ctx context.Context, limit int64) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Level,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogsRange = `-- name: GetLogsRange :many
SELECT id, timestamp, level, message
FROM logs
WHERE timestamp >= ? AND timestamp <= ?
ORDER BY id ASC
`

type GetLogsRangeParams struct {
	Timestamp   string
	Timestamp_2 string
}

func (q *Queries) GetLogsRange(ctx context.Context, arg GetLogsRangeParams) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getLogsRange, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Level,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessedMessageIDs = `-- name: GetProcessedMessageIDs :many

SELECT message_id FROM processed_emails
WHERE account_id = ? AND message_id IN (/*SLICE:message_ids*/?)
`

type GetProcessedMessageIDsParams struct {
	AccountID int64
	MessageID string
}

// ============================================================
// Processed Emails
// ============================================================
func (q *Queries) GetProcessedMessageIDs(ctx context.Context, arg GetProcessedMessageIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getProcessedMessageIDs, arg.AccountID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message_id string
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrompt = `-- name: GetPrompt :one
SELECT id, name, instructions, label_name, active, created_at,
       action_archive, action_spam, action_trash, action_mark_read,
       sort_order, stop_processing, account_id
FROM prompts WHERE id = ? LIMIT 1
`

func (q *Queries) GetPrompt(ctx context.Context, id int64) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, getPrompt, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Instructions,
		&i.LabelName,
		&i.Active,
		&i.CreatedAt,
		&i.ActionArchive,
		&i.ActionSpam,
		&i.ActionTrash,
		&i.ActionMarkRead,
		&i.SortOrder,
		&i.StopProcessing,
		&i.AccountID,
	)
	return i, err
}

const getPromptIDsByMessageID = `-- name: GetPromptIDsByMessageID :many
SELECT DISTINCT prompt_id FROM categorization_history
WHERE message_id = ? AND prompt_id IS NOT NULL
`

func (q *Queries) GetPromptIDsByMessageID(ctx context.Context, messageID string) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, getPromptIDsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt64
	for rows.Next() {
		var prompt_id sql.NullInt64
		if err := rows.Scan(&prompt_id); err != nil {
			return nil, err
		}
		items = append(items, prompt_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromptSuggestion = `-- name: GetPromptSuggestion :one
SELECT id, created_at, updated_at, prompt_id, correction_id, trigger_kind,
       message_id, email_subject, email_sender, email_body_snapshot,
       original_instructions, suggested_instructions, conversation_json,
       user_comment, status
FROM prompt_suggestions WHERE id = ? LIMIT 1
`

func (q *Queries) GetPromptSuggestion(ctx context.Context, id int64) (PromptSuggestion, error) {
	row := q.db.QueryRowContext(ctx, getPromptSuggestion, id)
	var i PromptSuggestion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptID,
		&i.CorrectionID,
		&i.TriggerKind,
		&i.MessageID,
		&i.EmailSubject,
		&i.EmailSender,
		&i.EmailBodySnapshot,
		&i.OriginalInstructions,
		&i.SuggestedInstructions,
		&i.ConversationJson,
		&i.UserComment,
		&i.Status,
	)
	return i, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one

SELECT version FROM schema_version LIMIT 1
`

// ============================================================
// Schema version
// ============================================================
func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getSetting = `-- name: GetSetting :one

SELECT value FROM settings WHERE key = ? LIMIT 1
`

// ============================================================
// Settings
// ============================================================
func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const hasGlobalRetention = `-- name: HasGlobalRetention :one
SELECT EXISTS(SELECT 1 FROM account_retention WHERE account_id = ?) AS exists_val
`

func (q *Queries) HasGlobalRetention(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasGlobalRetention, accountID)
	var exists_val int64
	err := row.Scan(&exists_val)
	return exists_val, err
}

const insertEmailCorrection = `-- name: InsertEmailCorrection :one

INSERT INTO email_corrections (account_id, message_id, added_prompts, removed_prompts, current_prompt_ids, note)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertEmailCorrectionParams struct {
	AccountID        int64
	MessageID        string
	AddedPrompts     string
	RemovedPrompts   string
	CurrentPromptIds string
	Note             string
}

// ============================================================
// Email Corrections
// ============================================================
func (q *Queries) InsertEmailCorrection(ctx context.Context, arg InsertEmailCorrectionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEmailCorrection,
		arg.AccountID,
		arg.MessageID,
		arg.AddedPrompts,
		arg.RemovedPrompts,
		arg.CurrentPromptIds,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPromptSuggestion = `-- name: InsertPromptSuggestion :one

INSERT INTO prompt_suggestions
    (prompt_id, correction_id, trigger_kind, message_id, email_subject, email_sender, email_body_snapshot, original_instructions, suggested_instructions, conversation_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertPromptSuggestionParams struct {
	PromptID              int64
	CorrectionID          sql.NullInt64
	TriggerKind           string
	MessageID             string
	EmailSubject          string
	EmailSender           string
	EmailBodySnapshot     string
	OriginalInstructions  string
	SuggestedInstructions string
	ConversationJson      string
}

// ============================================================
// Prompt Suggestions
// ============================================================
func (q *Queries) InsertPromptSuggestion(ctx context.Context, arg InsertPromptSuggestionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPromptSuggestion,
		arg.PromptID,
		arg.CorrectionID,
		arg.TriggerKind,
		arg.MessageID,
		arg.EmailSubject,
		arg.EmailSender,
		arg.EmailBodySnapshot,
		arg.OriginalInstructions,
		arg.SuggestedInstructions,
		arg.ConversationJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const labelRetentionExists = `-- name: LabelRetentionExists :one
SELECT EXISTS(SELECT 1 FROM label_retention WHERE account_id = ? AND label_name = ?) AS exists_val
`

type LabelRetentionExistsParams struct {
	AccountID int64
	LabelName string
}

func (q *Queries) LabelRetentionExists(ctx context.Context, arg LabelRetentionExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, labelRetentionExists, arg.AccountID, arg.LabelName)
	var exists_val int64
	err := row.Scan(&exists_val)
	return exists_val, err
}

const listAccounts = `-- name: ListAccounts :many

SELECT id, email, credentials_json, added_at, last_scan_at, active
FROM accounts
ORDER BY added_at DESC
`

// ============================================================
// Accounts
// ============================================================
func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CredentialsJson,
			&i.AddedAt,
			&i.LastScanAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsSafe = `-- name: ListAccountsSafe :many
SELECT id, email, added_at, last_scan_at, active
FROM accounts
ORDER BY added_at DESC
`

type ListAccountsSafeRow struct {
	ID         int64
	Email      string
	AddedAt    string
	LastScanAt sql.NullString
	Active     int64
}

func (q *Queries) ListAccountsSafe(ctx context.Context) ([]ListAccountsSafeRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsSafe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsSafeRow
	for rows.Next() {
		var i ListAccountsSafeRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.AddedAt,
			&i.LastScanAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePrompts = `-- name: ListActivePrompts :many
SELECT id, name, instructions, label_name, active, created_at,
       action_archive, action_spam, action_trash, action_mark_read,
       sort_order, stop_processing, account_id
FROM prompts
WHERE active = 1
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListActivePrompts(ctx context.Context) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listActivePrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Instructions,
			&i.LabelName,
			&i.Active,
			&i.CreatedAt,
			&i.ActionArchive,
			&i.ActionSpam,
			&i.ActionTrash,
			&i.ActionMarkRead,
			&i.SortOrder,
			&i.StopProcessing,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePromptsByAccount = `-- name: ListActivePromptsByAccount :many
SELECT id, name, instructions, label_name, active, created_at,
       action_archive, action_spam, action_trash, action_mark_read,
       sort_order, stop_processing, account_id
FROM prompts
WHERE active = 1 AND (account_id = ? OR account_id IS NULL)
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListActivePromptsByAccount(ctx context.Context, accountID sql.NullInt64) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listActivePromptsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Instructions,
			&i.LabelName,
			&i.Active,
			&i.CreatedAt,
			&i.ActionArchive,
			&i.ActionSpam,
			&i.ActionTrash,
			&i.ActionMarkRead,
			&i.SortOrder,
			&i.StopProcessing,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptSuggestions = `-- name: ListPromptSuggestions :many
SELECT id, created_at, updated_at, prompt_id, correction_id, trigger_kind,
       message_id, email_subject, email_sender, email_body_snapshot,
       original_instructions, suggested_instructions, conversation_json,
       user_comment, status
FROM prompt_suggestions
WHERE status != 'dismissed'
ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END ASC, id DESC
`

func (q *Queries) ListPromptSuggestions(ctx context.Context) ([]PromptSuggestion, error) {
	rows, err := q.db.QueryContext(ctx, listPromptSuggestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptSuggestion
	for rows.Next() {
		var i PromptSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PromptID,
			&i.CorrectionID,
			&i.TriggerKind,
			&i.MessageID,
			&i.EmailSubject,
			&i.EmailSender,
			&i.EmailBodySnapshot,
			&i.OriginalInstructions,
			&i.SuggestedInstructions,
			&i.ConversationJson,
			&i.UserComment,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrompts = `-- name: ListPrompts :many

SELECT id, name, instructions, label_name, active, created_at,
       action_archive, action_spam, action_trash, action_mark_read,
       sort_order, stop_processing, account_id
FROM prompts
ORDER BY sort_order ASC, id ASC
`

// ============================================================
// Prompts
// ============================================================
func (q *Queries) ListPrompts(ctx context.Context) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Instructions,
			&i.LabelName,
			&i.Active,
			&i.CreatedAt,
			&i.ActionArchive,
			&i.ActionSpam,
			&i.ActionTrash,
			&i.ActionMarkRead,
			&i.SortOrder,
			&i.StopProcessing,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptsByAccount = `-- name: ListPromptsByAccount :many
SELECT id, name, instructions, label_name, active, created_at,
       action_archive, action_spam, action_trash, action_mark_read,
       sort_order, stop_processing, account_id
FROM prompts
WHERE account_id = ? OR account_id IS NULL
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListPromptsByAccount(ctx context.Context, accountID sql.NullInt64) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPromptsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Instructions,
			&i.LabelName,
			&i.Active,
			&i.CreatedAt,
			&i.ActionArchive,
			&i.ActionSpam,
			&i.ActionTrash,
			&i.ActionMarkRead,
			&i.SortOrder,
			&i.StopProcessing,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProcessed = `-- name: MarkProcessed :exec
;

INSERT INTO processed_emails (account_id, message_id)
VALUES (?, ?)
ON CONFLICT(account_id, message_id) DO NOTHING
`

type MarkProcessedParams struct {
	AccountID int64
	MessageID string
}

func (q *Queries) MarkProcessed(ctx context.Context, arg MarkProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markProcessed, arg.AccountID, arg.MessageID)
	return err
}

const maxPromptSortOrder = `-- name: MaxPromptSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) FROM prompts
`

func (q *Queries) MaxPromptSortOrder(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxPromptSortOrder)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const promptExistsForAccount = `-- name: PromptExistsForAccount :one
SELECT EXISTS(SELECT 1 FROM prompts WHERE name = ? AND account_id = ?) AS exists_val
`

type PromptExistsForAccountParams struct {
	Name      string
	AccountID sql.NullInt64
}

func (q *Queries) PromptExistsForAccount(ctx context.Context, arg PromptExistsForAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, promptExistsForAccount, arg.Name, arg.AccountID)
	var exists_val int64
	err := row.Scan(&exists_val)
	return exists_val, err
}

const promptExistsGlobal = `-- name: PromptExistsGlobal :one
SELECT EXISTS(SELECT 1 FROM prompts WHERE name = ? AND account_id IS NULL) AS exists_val
`

func (q *Queries) PromptExistsGlobal(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, promptExistsGlobal, name)
	var exists_val int64
	err := row.Scan(&exists_val)
	return exists_val, err
}

const seedSetting = `-- name: SeedSetting :exec
INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)
`

type SeedSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SeedSetting(ctx context.Context, arg SeedSettingParams) error {
	_, err := q.db.ExecContext(ctx, seedSetting, arg.Key, arg.Value)
	return err
}

const setGlobalRetention = `-- name: SetGlobalRetention :exec
INSERT INTO account_retention (account_id, global_days) VALUES (?, ?)
ON CONFLICT(account_id) DO UPDATE SET global_days = excluded.global_days
`

type SetGlobalRetentionParams struct {
	AccountID  int64
	GlobalDays sql.NullInt64
}

func (q *Queries) SetGlobalRetention(ctx context.Context, arg SetGlobalRetentionParams) error {
	_, err := q.db.ExecContext(ctx, setGlobalRetention, arg.AccountID, arg.GlobalDays)
	return err
}

const setSchemaVersion = `-- name: SetSchemaVersion :exec
UPDATE schema_version SET version = ?
`

func (q *Queries) SetSchemaVersion(ctx context.Context, version int64) error {
	_, err := q.db.ExecContext(ctx, setSchemaVersion, version)
	return err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const toggleAccount = `-- name: ToggleAccount :one
UPDATE accounts SET active = 1 - active WHERE id = ? RETURNING active
`

func (q *Queries) ToggleAccount(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, toggleAccount, id)
	var active int64
	err := row.Scan(&active)
	return active, err
}

const togglePrompt = `-- name: TogglePrompt :one
UPDATE prompts SET active = 1 - active WHERE id = ? RETURNING active
`

func (q *Queries) TogglePrompt(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, togglePrompt, id)
	var active int64
	err := row.Scan(&active)
	return active, err
}

const trimHistory = `-- name: TrimHistory :exec
DELETE FROM categorization_history WHERE timestamp < ?
`

func (q *Queries) TrimHistory(ctx context.Context, timestamp string) error {
	_, err := q.db.ExecContext(ctx, trimHistory, timestamp)
	return err
}

const trimLlmDebug = `-- name: TrimLlmDebug :exec
DELETE FROM llm_debug WHERE id NOT IN (SELECT id FROM llm_debug ORDER BY id DESC LIMIT 3)
`

func (q *Queries) TrimLlmDebug(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, trimLlmDebug)
	return err
}

const deleteIncompleteLlmDebug = `-- name: DeleteIncompleteLlmDebug :exec
DELETE FROM llm_debug WHERE gmail_raw = '' OR llm_request = ''
`

func (q *Queries) DeleteIncompleteLlmDebug(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteIncompleteLlmDebug)
	return err
}

const trimLogs = `-- name: TrimLogs :exec
DELETE FROM logs WHERE timestamp < ?
`

func (q *Queries) TrimLogs(ctx context.Context, timestamp string) error {
	_, err := q.db.ExecContext(ctx, trimLogs, timestamp)
	return err
}

const trimProcessedEmails = `-- name: TrimProcessedEmails :exec
DELETE FROM processed_emails
WHERE processed_at IS NOT NULL AND processed_at < ?
`

func (q *Queries) TrimProcessedEmails(ctx context.Context, processedAt sql.NullString) error {
	_, err := q.db.ExecContext(ctx, trimProcessedEmails, processedAt)
	return err
}

const updateAccountCredentials = `-- name: UpdateAccountCredentials :exec
UPDATE accounts SET credentials_json = ? WHERE id = ?
`

type UpdateAccountCredentialsParams struct {
	CredentialsJson string
	ID              int64
}

func (q *Queries) UpdateAccountCredentials(ctx context.Context, arg UpdateAccountCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountCredentials, arg.CredentialsJson, arg.ID)
	return err
}

const updateLastScan = `-- name: UpdateLastScan :exec
UPDATE accounts SET last_scan_at = strftime('%Y-%m-%d %H:%M:%S', 'now') WHERE id = ?
`

func (q *Queries) UpdateLastScan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateLastScan, id)
	return err
}

const updatePrompt = `-- name: UpdatePrompt :exec
UPDATE prompts SET
    name = ?,
    instructions = ?,
    label_name = ?,
    action_archive = ?,
    action_spam = ?,
    action_trash = ?,
    action_mark_read = ?,
    stop_processing = ?,
    account_id = ?
WHERE id = ?
`

type UpdatePromptParams struct {
	Name           string
	Instructions   string
	LabelName      string
	ActionArchive  int64
	ActionSpam     int64
	ActionTrash    int64
	ActionMarkRead int64
	StopProcessing int64
	AccountID      sql.NullInt64
	ID             int64
}

func (q *Queries) UpdatePrompt(ctx context.Context, arg UpdatePromptParams) error {
	_, err := q.db.ExecContext(ctx, updatePrompt,
		arg.Name,
		arg.Instructions,
		arg.LabelName,
		arg.ActionArchive,
		arg.ActionSpam,
		arg.ActionTrash,
		arg.ActionMarkRead,
		arg.StopProcessing,
		arg.AccountID,
		arg.ID,
	)
	return err
}

const updatePromptInstructions = `-- name: UpdatePromptInstructions :exec
UPDATE prompts SET instructions = ? WHERE id = ?
`

type UpdatePromptInstructionsParams struct {
	Instructions string
	ID           int64
}

func (q *Queries) UpdatePromptInstructions(ctx context.Context, arg UpdatePromptInstructionsParams) error {
	_, err := q.db.ExecContext(ctx, updatePromptInstructions, arg.Instructions, arg.ID)
	return err
}

const updatePromptSortOrder = `-- name: UpdatePromptSortOrder :exec
UPDATE prompts SET sort_order = ? WHERE id = ?
`

type UpdatePromptSortOrderParams struct {
	SortOrder int64
	ID        int64
}

func (q *Queries) UpdatePromptSortOrder(ctx context.Context, arg UpdatePromptSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updatePromptSortOrder, arg.SortOrder, arg.ID)
	return err
}

const updatePromptSuggestion = `-- name: UpdatePromptSuggestion :exec
UPDATE prompt_suggestions SET
    suggested_instructions = ?,
    conversation_json = ?,
    user_comment = ?,
    status = 'pending',
    updated_at = strftime('%Y-%m-%d %H:%M:%S', 'now')
WHERE id = ?
`

type UpdatePromptSuggestionParams struct {
	SuggestedInstructions string
	ConversationJson      string
	UserComment           string
	ID                    int64
}

func (q *Queries) UpdatePromptSuggestion(ctx context.Context, arg UpdatePromptSuggestionParams) error {
	_, err := q.db.ExecContext(ctx, updatePromptSuggestion,
		arg.SuggestedInstructions,
		arg.ConversationJson,
		arg.UserComment,
		arg.ID,
	)
	return err
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO accounts (email, credentials_json, active)
VALUES (?, ?, 1)
ON CONFLICT(email) DO UPDATE SET credentials_json = excluded.credentials_json, active = 1
RETURNING id
`

type UpsertAccountParams struct {
	Email           string
	CredentialsJson string
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertAccount, arg.Email, arg.CredentialsJson)
	var id int64
	err := row.Scan(&id)
	return id, err
}
